tap "adoptopenjdk/openjdk"
tap "caius/jo"
tap "ethereum/ethereum"
tap "github/gh"
tap "greymd/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "knqyf263/pet"
tap "olafurpg/scalafmt"
tap "rcmdnk/file"
tap "sanemat/font"
brew "openjdk", link: true
brew "ammonite-repl"
brew "libyaml"
brew "xz"
brew "ansible"
brew "ant"
brew "anyenv"
brew "arp-scan"
brew "autoconf"
brew "bash"
brew "bat"
brew "icu4c", link: true
brew "gettext"
brew "libffi", link: true
brew "glib"
brew "pkg-config"
brew "circleci"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "curl", link: true
brew "diffutils"
brew "direnv"
brew "docker"
brew "docker-clean"
brew "dockutil"
brew "duti"
brew "elm"
brew "erlang"
brew "exiftool"
brew "mpfr"
brew "gcc"
brew "libevent"
brew "figlet"
brew "gobject-introspection"
brew "harfbuzz"
brew "libtool"
brew "fontforge"
brew "freetds"
brew "fzf"
brew "gawk"
brew "gd"
brew "gdk-pixbuf"
brew "geoipupdate"
brew "gh"
brew "libidn"
brew "ghq"
brew "gibo"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "glances"
brew "gnu-sed"
brew "gperftools"
brew "graphicsmagick"
brew "graphviz"
brew "grep"
brew "gzip"
brew "highlight"
brew "htop"
brew "httpie"
brew "httpstat"
brew "hub"
brew "ilmbase"
brew "imagemagick"
brew "iproute2mac"
brew "jo"
brew "oniguruma"
brew "jq"
brew "jsvc"
brew "kotlin"
brew "lame"
brew "lftp"
brew "libev"
brew "libiconv", link: true
brew "libmaxminddb"
brew "libsodium"
brew "libusb"
brew "libvo-aacenc"
brew "libxslt", link: true
brew "lv"
brew "lzip"
brew "mad"
brew "make"
brew "mas"
brew "md5sha1sum", link: false
brew "minikube"
brew "mkcert"
brew "moreutils"
brew "multitail"
brew "mycli"
brew "mysql@5.7", restart_service: true, link: true
brew "neovim"
brew "nkf"
brew "nmap"
brew "nodebrew"
brew "nss"
brew "pandoc"
brew "peco"
brew "pgcli"
brew "plantuml"
brew "podman"
brew "qt"
brew "postgresql", link: false
brew "proctools"
brew "protobuf"
brew "python@3.8"
brew "reattach-to-user-namespace"
brew "rebar3"
brew "redis"
brew "rlwrap"
brew "rocksdb"
brew "rsync"
brew "ruby", link: true
brew "rustup-init"
brew "sbt"
brew "scalaenv", args: ["HEAD"]
brew "socat"
brew "source-highlight"
brew "stern"
brew "td"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "the_silver_searcher"
brew "tig"
brew "utf8proc"
brew "tmux"
brew "translate-shell"
brew "tree"
brew "vim"
brew "vips"
brew "watch"
brew "wget"
brew "yarn"
brew "zlib", link: true
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "greymd/tools/tmux-xpanes"
brew "knqyf263/pet/pet"
brew "rcmdnk/file/brew-file"
brew "sanemat/font/ricty"
mas "CotEditor", id: 1024640650
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TweetDeck", id: 485812721
