# 基本は github.com のレポジトリーを指定するだけ

# repo = has('lua') ? 'Shougo/neocomplete' : 'Shougo/neocomplcache'
#
#
[[plugins]]
repo = 'tomlion/vim-solidity'
on_ft = ['solidity']
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'
on_ft = ['erlang']
[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'
on_ft = ['erlang']
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']
[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']
[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'
on_cmd = ['Unite']
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
[[plugins]]
repo = 'h1mesuke/unite-outline'
on_source = ['unite.vim']
[[plugins]]
repo = 'tsukkee/unite-help'
on_source = ['unite.vim']
[[plugins]]
repo = "alfredodeza/khuno.vim"
on_ft = ['python', 'python3']
[[plugins]]
repo = "vim-scripts/indentpython.vim"
on_ft = ['python', 'python3']
on_i = 1
# [[plugins]]
# repo = "lambdalisue/vim-django-support"
# on_ft = ['python', 'python3']
# [[plugins]]
# repo = "mjbrownie/django-template-textobjects"
# on_ft = ['python', 'python3']
[[plugins]]
repo = "kana/vim-textobj-user"
on_ft = ['python', 'python3']
# [[plugins]]
# repo = "edsono/vim-matchit"
# on_ft = ['python', 'python3']
# [[plugins]]
# repo = "lambdalisue/vim-pyenv"
# on_ft = ['python', 'python3']
[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python', 'python3']
on_i = 1
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']
on_i = 1
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['html', 'css', 'javascript']
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['html', 'css', 'javascript']
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts','tsx', 'typescript', 'typescript.jsx']
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['ts','tsx', 'typescript', 'typescript.jsx']
[[plugins]]
repo = 'thinca/vim-quickrun'
# on_cmd = ['QuickRun']
on_map = [['n', '<Plug>']]
hook_add = 'nmap <silent> <Space>r <Plug>(quickrun)'
[[plugins]]
repo = "mattn/gist-vim"
on_cmd = ['Gist']
[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = ['tex']
[[plugins]]
repo = 'gre/play2vim'
on_ft = ['scala']
[[plugins]]
repo = "dag/vim2hs"
on_ft = ['haskell']
[[plugins]]
repo = "eagletmt/unite-haddock"
on_ft = ['haskell']
[[plugins]]
repo = "ujihisa/neco-ghc"
on_ft = ['haskell']
[[plugins]]
repo = "ujihisa/unite-haskellimport"
on_ft = ['haskell']
[[plugins]]
repo = "wlangstroth/vim-racket"
on_ft = ['rkt', 'racket']
[[plugins]]
repo = "vim-scripts/dbext.vim"
on_ft = ['sql']
[[plugins]]
repo = 'bbatsov/rubocop'
on_ft = ['ruby']
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
[[plugins]]
repo = 'kannokanno/previm'
on_cmd = ['Previm']
[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['Previm']
[[plugins]]
repo = "Shougo/vimproc.vim"
# on_source = ['QuickRun']
build = 'make'
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'roxma/nvim-yarp'

# [[plugins]]
# repo = 'Shougo/neocomplete'
# on_i = 1
[[plugins]]
repo = 'superbrothers/vim-quickrun-markdown-gfm'
on_ft = ['md', 'markdown']
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md', 'markdown']
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']
